export type FieldDef = {
  key: string;
  label: string;
  placeholder: string;
  type: "text" | "number" | "email" | "date" | "select";
  options?: string[];
};

export type IndustryConfig = {
  name: string;
  emoji: string;
  color: string;
  stages: string[];
  stageColors: Record<string, string>;
  customFields: FieldDef[];
  dealLabel: string;
  sellerLabel: string;
  amountLabel: string;
};

const INDUSTRY_CONFIGS: Record<string, IndustryConfig> = {
  "real-estate": {
    name: "Real Estate",
    emoji: "🏠",
    color: "bg-blue-600",
    dealLabel: "Property",
    sellerLabel: "Seller",
    amountLabel: "Assignment Fee",
    stages: ["New Lead", "Contacted", "Offer Made", "Under Contract", "Closed Won"],
    stageColors: {
      "New Lead": "bg-slate-100 text-slate-700",
      "Contacted": "bg-blue-100 text-blue-700",
      "Offer Made": "bg-yellow-100 text-yellow-700",
      "Under Contract": "bg-purple-100 text-purple-700",
      "Closed Won": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "ARV", placeholder: "285000", type: "number" },
      { key: "offer", label: "Asking Price", placeholder: "195000", type: "number" },
      { key: "address", label: "Property Address", placeholder: "123 Main St", type: "text" },
      { key: "amount", label: "Assignment Fee", placeholder: "15000", type: "number" },
      { key: "contact_email", label: "Seller Email", placeholder: "seller@email.com", type: "email" },
      { key: "next_follow_up", label: "Follow-up Date", placeholder: "", type: "date" },
    ],
  },
  "insurance": {
    name: "Insurance",
    emoji: "🛡️",
    color: "bg-emerald-600",
    dealLabel: "Policy",
    sellerLabel: "Client",
    amountLabel: "Premium",
    stages: ["New Lead", "Quoted", "Proposal Sent", "Negotiating", "Closed Won", "Closed Lost"],
    stageColors: {
      "New Lead": "bg-slate-100 text-slate-700",
      "Quoted": "bg-blue-100 text-blue-700",
      "Proposal Sent": "bg-yellow-100 text-yellow-700",
      "Negotiating": "bg-orange-100 text-orange-700",
      "Closed Won": "bg-emerald-100 text-emerald-700",
      "Closed Lost": "bg-red-100 text-red-700",
    },
    customFields: [
      { key: "arv", label: "Coverage Amount", placeholder: "500000", type: "number" },
      { key: "offer", label: "Annual Premium", placeholder: "2400", type: "number" },
      { key: "amount", label: "Commission", placeholder: "480", type: "number" },
      { key: "address", label: "Policy Type", placeholder: "Auto / Home / Life / Health", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Renewal Date", placeholder: "", type: "date" },
    ],
  },
  "mortgage": {
    name: "Mortgage & Lending",
    emoji: "🏦",
    color: "bg-violet-600",
    dealLabel: "Loan",
    sellerLabel: "Borrower",
    amountLabel: "Loan Amount",
    stages: ["Inquiry", "Pre-Qualified", "Application", "Processing", "Underwriting", "Approved", "Funded"],
    stageColors: {
      "Inquiry": "bg-slate-100 text-slate-700",
      "Pre-Qualified": "bg-blue-100 text-blue-700",
      "Application": "bg-indigo-100 text-indigo-700",
      "Processing": "bg-yellow-100 text-yellow-700",
      "Underwriting": "bg-orange-100 text-orange-700",
      "Approved": "bg-purple-100 text-purple-700",
      "Funded": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Loan Amount", placeholder: "350000", type: "number" },
      { key: "offer", label: "Property Value", placeholder: "400000", type: "number" },
      { key: "amount", label: "Origination Fee", placeholder: "3500", type: "number" },
      { key: "address", label: "Property Address", placeholder: "123 Main St", type: "text" },
      { key: "contact_email", label: "Borrower Email", placeholder: "borrower@email.com", type: "email" },
      { key: "next_follow_up", label: "Close Date", placeholder: "", type: "date" },
    ],
  },
  "auto": {
    name: "Automotive",
    emoji: "🚗",
    color: "bg-red-600",
    dealLabel: "Vehicle",
    sellerLabel: "Customer",
    amountLabel: "Sale Price",
    stages: ["New Lead", "Appointment Set", "Test Drive", "Negotiating", "Financing", "Sold"],
    stageColors: {
      "New Lead": "bg-slate-100 text-slate-700",
      "Appointment Set": "bg-blue-100 text-blue-700",
      "Test Drive": "bg-yellow-100 text-yellow-700",
      "Negotiating": "bg-orange-100 text-orange-700",
      "Financing": "bg-purple-100 text-purple-700",
      "Sold": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "MSRP", placeholder: "35000", type: "number" },
      { key: "offer", label: "Trade-in Value", placeholder: "8000", type: "number" },
      { key: "amount", label: "Sale Price", placeholder: "32000", type: "number" },
      { key: "address", label: "Vehicle (Year/Make/Model/VIN)", placeholder: "2023 Toyota Camry", type: "text" },
      { key: "contact_email", label: "Customer Email", placeholder: "customer@email.com", type: "email" },
      { key: "next_follow_up", label: "Follow-up Date", placeholder: "", type: "date" },
    ],
  },
  "solar": {
    name: "Solar Energy",
    emoji: "☀️",
    color: "bg-yellow-500",
    dealLabel: "Installation",
    sellerLabel: "Homeowner",
    amountLabel: "Contract Value",
    stages: ["New Lead", "Site Survey", "Proposal", "Contract Signed", "Permitting", "Installation", "PTO"],
    stageColors: {
      "New Lead": "bg-slate-100 text-slate-700",
      "Site Survey": "bg-blue-100 text-blue-700",
      "Proposal": "bg-yellow-100 text-yellow-700",
      "Contract Signed": "bg-orange-100 text-orange-700",
      "Permitting": "bg-purple-100 text-purple-700",
      "Installation": "bg-indigo-100 text-indigo-700",
      "PTO": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "System Size (kW)", placeholder: "8.5", type: "number" },
      { key: "offer", label: "Monthly Electric Bill", placeholder: "250", type: "number" },
      { key: "amount", label: "Contract Value", placeholder: "28000", type: "number" },
      { key: "address", label: "Property Address", placeholder: "123 Main St", type: "text" },
      { key: "contact_email", label: "Homeowner Email", placeholder: "owner@email.com", type: "email" },
      { key: "next_follow_up", label: "Install Date", placeholder: "", type: "date" },
    ],
  },
  "financial": {
    name: "Financial Services",
    emoji: "📈",
    color: "bg-blue-700",
    dealLabel: "Client",
    sellerLabel: "Client",
    amountLabel: "AUM",
    stages: ["Prospect", "Initial Meeting", "Proposal", "Compliance Review", "Onboarding", "Active Client"],
    stageColors: {
      "Prospect": "bg-slate-100 text-slate-700",
      "Initial Meeting": "bg-blue-100 text-blue-700",
      "Proposal": "bg-yellow-100 text-yellow-700",
      "Compliance Review": "bg-orange-100 text-orange-700",
      "Onboarding": "bg-purple-100 text-purple-700",
      "Active Client": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Assets Under Management", placeholder: "500000", type: "number" },
      { key: "offer", label: "Annual Fee (%)", placeholder: "1.0", type: "number" },
      { key: "amount", label: "Annual Revenue", placeholder: "5000", type: "number" },
      { key: "address", label: "Investment Focus", placeholder: "Retirement / Growth / Income", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Review Date", placeholder: "", type: "date" },
    ],
  },
  "legal": {
    name: "Legal",
    emoji: "⚖️",
    color: "bg-slate-700",
    dealLabel: "Case",
    sellerLabel: "Client",
    amountLabel: "Case Value",
    stages: ["Inquiry", "Consultation", "Retained", "Discovery", "Negotiation", "Trial", "Closed"],
    stageColors: {
      "Inquiry": "bg-slate-100 text-slate-700",
      "Consultation": "bg-blue-100 text-blue-700",
      "Retained": "bg-indigo-100 text-indigo-700",
      "Discovery": "bg-yellow-100 text-yellow-700",
      "Negotiation": "bg-orange-100 text-orange-700",
      "Trial": "bg-red-100 text-red-700",
      "Closed": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Case Value", placeholder: "100000", type: "number" },
      { key: "offer", label: "Retainer Amount", placeholder: "5000", type: "number" },
      { key: "amount", label: "Fees Earned", placeholder: "0", type: "number" },
      { key: "address", label: "Case Type", placeholder: "Personal Injury / Family / Criminal", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Court Date", placeholder: "", type: "date" },
    ],
  },
  "recruiting": {
    name: "Recruiting",
    emoji: "🎯",
    color: "bg-indigo-600",
    dealLabel: "Candidate",
    sellerLabel: "Candidate",
    amountLabel: "Placement Fee",
    stages: ["New Candidate", "Screening", "Submitted", "Interview", "Offer Extended", "Placed", "Rejected"],
    stageColors: {
      "New Candidate": "bg-slate-100 text-slate-700",
      "Screening": "bg-blue-100 text-blue-700",
      "Submitted": "bg-indigo-100 text-indigo-700",
      "Interview": "bg-yellow-100 text-yellow-700",
      "Offer Extended": "bg-orange-100 text-orange-700",
      "Placed": "bg-emerald-100 text-emerald-700",
      "Rejected": "bg-red-100 text-red-700",
    },
    customFields: [
      { key: "arv", label: "Salary", placeholder: "85000", type: "number" },
      { key: "offer", label: "Placement Fee", placeholder: "12750", type: "number" },
      { key: "amount", label: "Fee Earned", placeholder: "0", type: "number" },
      { key: "address", label: "Position / Skills", placeholder: "Senior Developer - React", type: "text" },
      { key: "contact_email", label: "Candidate Email", placeholder: "candidate@email.com", type: "email" },
      { key: "next_follow_up", label: "Interview Date", placeholder: "", type: "date" },
    ],
  },
  "healthcare": {
    name: "Healthcare",
    emoji: "🏥",
    color: "bg-cyan-600",
    dealLabel: "Patient",
    sellerLabel: "Patient",
    amountLabel: "Treatment Value",
    stages: ["New Patient", "Consultation", "Treatment Plan", "In Treatment", "Follow-up", "Discharged"],
    stageColors: {
      "New Patient": "bg-slate-100 text-slate-700",
      "Consultation": "bg-blue-100 text-blue-700",
      "Treatment Plan": "bg-yellow-100 text-yellow-700",
      "In Treatment": "bg-orange-100 text-orange-700",
      "Follow-up": "bg-purple-100 text-purple-700",
      "Discharged": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Treatment Value", placeholder: "5000", type: "number" },
      { key: "offer", label: "Insurance Coverage", placeholder: "4000", type: "number" },
      { key: "amount", label: "Patient Responsibility", placeholder: "1000", type: "number" },
      { key: "address", label: "Insurance Provider", placeholder: "Blue Cross / Aetna", type: "text" },
      { key: "contact_email", label: "Patient Email", placeholder: "patient@email.com", type: "email" },
      { key: "next_follow_up", label: "Next Appointment", placeholder: "", type: "date" },
    ],
  },
  "construction": {
    name: "Construction",
    emoji: "🏗️",
    color: "bg-orange-600",
    dealLabel: "Project",
    sellerLabel: "Client",
    amountLabel: "Contract Value",
    stages: ["Lead", "Estimate", "Proposal Sent", "Contract Signed", "In Progress", "Punch List", "Completed"],
    stageColors: {
      "Lead": "bg-slate-100 text-slate-700",
      "Estimate": "bg-blue-100 text-blue-700",
      "Proposal Sent": "bg-yellow-100 text-yellow-700",
      "Contract Signed": "bg-orange-100 text-orange-700",
      "In Progress": "bg-indigo-100 text-indigo-700",
      "Punch List": "bg-purple-100 text-purple-700",
      "Completed": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Bid Amount", placeholder: "75000", type: "number" },
      { key: "offer", label: "Material Cost", placeholder: "30000", type: "number" },
      { key: "amount", label: "Contract Value", placeholder: "75000", type: "number" },
      { key: "address", label: "Project Address", placeholder: "123 Main St", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Project Start Date", placeholder: "", type: "date" },
    ],
  },
  "consulting": {
    name: "Consulting",
    emoji: "💡",
    color: "bg-purple-600",
    dealLabel: "Engagement",
    sellerLabel: "Client",
    amountLabel: "Contract Value",
    stages: ["Prospect", "Discovery Call", "Proposal", "Negotiating", "Active", "Completed"],
    stageColors: {
      "Prospect": "bg-slate-100 text-slate-700",
      "Discovery Call": "bg-blue-100 text-blue-700",
      "Proposal": "bg-yellow-100 text-yellow-700",
      "Negotiating": "bg-orange-100 text-orange-700",
      "Active": "bg-indigo-100 text-indigo-700",
      "Completed": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Project Value", placeholder: "25000", type: "number" },
      { key: "offer", label: "Hourly Rate", placeholder: "200", type: "number" },
      { key: "amount", label: "Fees Earned", placeholder: "0", type: "number" },
      { key: "address", label: "Service Type", placeholder: "Strategy / Tech / Marketing", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Check-in Date", placeholder: "", type: "date" },
    ],
  },
  "ecommerce": {
    name: "E-Commerce",
    emoji: "🛒",
    color: "bg-pink-600",
    dealLabel: "Order/Deal",
    sellerLabel: "Customer",
    amountLabel: "Order Value",
    stages: ["New Lead", "Contacted", "Sample Sent", "Negotiating", "Order Placed", "Fulfilled"],
    stageColors: {
      "New Lead": "bg-slate-100 text-slate-700",
      "Contacted": "bg-blue-100 text-blue-700",
      "Sample Sent": "bg-yellow-100 text-yellow-700",
      "Negotiating": "bg-orange-100 text-orange-700",
      "Order Placed": "bg-purple-100 text-purple-700",
      "Fulfilled": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Order Value", placeholder: "5000", type: "number" },
      { key: "offer", label: "Product Cost", placeholder: "2000", type: "number" },
      { key: "amount", label: "Profit", placeholder: "3000", type: "number" },
      { key: "address", label: "Product / SKU", placeholder: "Product name or SKU", type: "text" },
      { key: "contact_email", label: "Customer Email", placeholder: "customer@email.com", type: "email" },
      { key: "next_follow_up", label: "Follow-up Date", placeholder: "", type: "date" },
    ],
  },
  "property-management": {
    name: "Property Management",
    emoji: "🏢",
    color: "bg-teal-600",
    dealLabel: "Property/Tenant",
    sellerLabel: "Tenant",
    amountLabel: "Monthly Rent",
    stages: ["Inquiry", "Showing", "Application", "Screening", "Approved", "Lease Signed", "Active Tenant"],
    stageColors: {
      "Inquiry": "bg-slate-100 text-slate-700",
      "Showing": "bg-blue-100 text-blue-700",
      "Application": "bg-yellow-100 text-yellow-700",
      "Screening": "bg-orange-100 text-orange-700",
      "Approved": "bg-purple-100 text-purple-700",
      "Lease Signed": "bg-indigo-100 text-indigo-700",
      "Active Tenant": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Monthly Rent", placeholder: "2500", type: "number" },
      { key: "offer", label: "Security Deposit", placeholder: "2500", type: "number" },
      { key: "amount", label: "Annual Revenue", placeholder: "30000", type: "number" },
      { key: "address", label: "Property Address", placeholder: "123 Main St Unit 1", type: "text" },
      { key: "contact_email", label: "Tenant Email", placeholder: "tenant@email.com", type: "email" },
      { key: "next_follow_up", label: "Lease End Date", placeholder: "", type: "date" },
    ],
  },
  "trucking": {
    name: "Trucking & Logistics",
    emoji: "🚛",
    color: "bg-blue-800",
    dealLabel: "Load",
    sellerLabel: "Shipper",
    amountLabel: "Load Rate",
    stages: ["Available Load", "Booked", "Dispatched", "In Transit", "Delivered", "Invoiced"],
    stageColors: {
      "Available Load": "bg-slate-100 text-slate-700",
      "Booked": "bg-blue-100 text-blue-700",
      "Dispatched": "bg-yellow-100 text-yellow-700",
      "In Transit": "bg-orange-100 text-orange-700",
      "Delivered": "bg-purple-100 text-purple-700",
      "Invoiced": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Load Rate", placeholder: "3500", type: "number" },
      { key: "offer", label: "Carrier Cost", placeholder: "2800", type: "number" },
      { key: "amount", label: "Profit", placeholder: "700", type: "number" },
      { key: "address", label: "Origin → Destination", placeholder: "Chicago IL → Dallas TX", type: "text" },
      { key: "contact_email", label: "Shipper Email", placeholder: "shipper@email.com", type: "email" },
      { key: "next_follow_up", label: "Delivery Date", placeholder: "", type: "date" },
    ],
  },
  "dental": {
    name: "Dental",
    emoji: "🦷",
    color: "bg-sky-500",
    dealLabel: "Patient",
    sellerLabel: "Patient",
    amountLabel: "Treatment Value",
    stages: ["New Patient", "Exam Scheduled", "Treatment Plan", "Scheduled", "In Treatment", "Follow-up"],
    stageColors: {
      "New Patient": "bg-slate-100 text-slate-700",
      "Exam Scheduled": "bg-blue-100 text-blue-700",
      "Treatment Plan": "bg-yellow-100 text-yellow-700",
      "Scheduled": "bg-orange-100 text-orange-700",
      "In Treatment": "bg-purple-100 text-purple-700",
      "Follow-up": "bg-emerald-100 text-emerald-700",
    },
    customFields: [
      { key: "arv", label: "Treatment Value", placeholder: "3000", type: "number" },
      { key: "offer", label: "Insurance Coverage", placeholder: "2000", type: "number" },
      { key: "amount", label: "Patient Balance", placeholder: "1000", type: "number" },
      { key: "address", label: "Treatment Type", placeholder: "Implant / Crown / Invisalign", type: "text" },
      { key: "contact_email", label: "Patient Email", placeholder: "patient@email.com", type: "email" },
      { key: "next_follow_up", label: "Next Appointment", placeholder: "", type: "date" },
    ],
  },
  "fitness": {
    name: "Fitness & Wellness",
    emoji: "💪",
    color: "bg-green-600",
    dealLabel: "Client",
    sellerLabel: "Client",
    amountLabel: "Package Value",
    stages: ["Inquiry", "Consultation", "Trial", "Enrolled", "Active", "Renewal Due"],
    stageColors: {
      "Inquiry": "bg-slate-100 text-slate-700",
      "Consultation": "bg-blue-100 text-blue-700",
      "Trial": "bg-yellow-100 text-yellow-700",
      "Enrolled": "bg-orange-100 text-orange-700",
      "Active": "bg-emerald-100 text-emerald-700",
      "Renewal Due": "bg-red-100 text-red-700",
    },
    customFields: [
      { key: "arv", label: "Package Value", placeholder: "1200", type: "number" },
      { key: "offer", label: "Monthly Rate", placeholder: "150", type: "number" },
      { key: "amount", label: "Revenue Earned", placeholder: "0", type: "number" },
      { key: "address", label: "Program Type", placeholder: "Personal Training / Group / Nutrition", type: "text" },
      { key: "contact_email", label: "Client Email", placeholder: "client@email.com", type: "email" },
      { key: "next_follow_up", label: "Renewal Date", placeholder: "", type: "date" },
    ],
  },
  "nonprofit": {
    name: "Nonprofit",
    emoji: "❤️",
    color: "bg-rose-600",
    dealLabel: "Donor/Grant",
    sellerLabel: "Donor",
    amountLabel: "Donation Amount",
    stages: ["Prospect", "Contacted", "Cultivating", "Ask Made", "Pledged", "Received", "Stewarding"],
    stageColors: {
      "Prospect": "bg-slate-100 text-slate-700",
      "Contacted": "bg-blue-100 text-blue-700",
      "Cultivating": "bg-yellow-100 text-yellow-700",
      "Ask Made": "bg-orange-100 text-orange-700",
      "Pledged": "bg-purple-100 text-purple-700",
      "Received": "bg-emerald-100 text-emerald-700",
      "Stewarding": "bg-teal-100 text-teal-700",
    },
    customFields: [
      { key: "arv", label: "Ask Amount", placeholder: "10000", type: "number" },
      { key: "offer", label: "Pledge Amount", placeholder: "5000", type: "number" },
      { key: "amount", label: "Received", placeholder: "0", type: "number" },
      { key: "address", label: "Fund / Program", placeholder: "General Fund / Capital Campaign", type: "text" },
      { key: "contact_email", label: "Donor Email", placeholder: "donor@email.com", type: "email" },
      { key: "next_follow_up", label: "Stewardship Date", placeholder: "", type: "date" },
    ],
  },
  "education": {
    name: "Education",
    emoji: "🎓",
    color: "bg-indigo-500",
    dealLabel: "Student/Client",
    sellerLabel: "Student",
    amountLabel: "Tuition",
    stages: ["Inquiry", "Consultation", "Enrolled", "Active", "Completed", "Alumni"],
    stageColors: {
      "Inquiry": "bg-slate-100 text-slate-700",
      "Consultation": "bg-blue-100 text-blue-700",
      "Enrolled": "bg-yellow-100 text-yellow-700",
      "Active": "bg-orange-100 text-orange-700",
      "Completed": "bg-emerald-100 text-emerald-700",
      "Alumni": "bg-purple-100 text-purple-700",
    },
    customFields: [
      { key: "arv", label: "Tuition Value", placeholder: "5000", type: "number" },
      { key: "offer", label: "Scholarship Amount", placeholder: "0", type: "number" },
      { key: "amount", label: "Revenue", placeholder: "5000", type: "number" },
      { key: "address", label: "Program / Course", placeholder: "MBA / Coding Bootcamp", type: "text" },
      { key: "contact_email", label: "Student Email", placeholder: "student@email.com", type: "email" },
      { key: "next_follow_up", label: "Start Date", placeholder: "", type: "date" },
    ],
  },
};

export function getIndustryConfig(industry: string): IndustryConfig {
  return INDUSTRY_CONFIGS[industry] || INDUSTRY_CONFIGS["real-estate"];
}

export default INDUSTRY_CONFIGS;
